// Generated by delombok at Mon Nov 28 21:50:33 CST 2022
package com.nukkitx.network.util;

import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.DatagramChannel;
import io.netty.channel.socket.ServerSocketChannel;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import java.util.concurrent.ThreadFactory;

public final class EventLoops {
    private static EventLoopGroup EVENT_LOOP_GROUP;
    private static final ThreadFactory EVENT_LOOP_FACTORY = NetworkThreadFactory.builder().format("Network Listener - #%d").daemon(true).build();
    private static final Class<? extends DatagramChannel> datagramChannel = NioDatagramChannel.class;
    private static final Class<? extends SocketChannel> socketChannel = NioSocketChannel.class;
    private static final Class<? extends ServerSocketChannel> serverSocketChannel = NioServerSocketChannel.class;

    public static EventLoopGroup commonGroup() {
        if (EVENT_LOOP_GROUP == null) {
            EVENT_LOOP_GROUP = newEventLoopGroup(0);
        }
        return EVENT_LOOP_GROUP;
    }

    public static EventLoopGroup newEventLoopGroup(int threads) {
        return new NioEventLoopGroup(threads, EVENT_LOOP_FACTORY);
    }

    @java.lang.SuppressWarnings("all")
    private EventLoops() {
        throw new java.lang.UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    @java.lang.SuppressWarnings("all")
    public static Class<? extends DatagramChannel> getDatagramChannel() {
        return EventLoops.datagramChannel;
    }

    @java.lang.SuppressWarnings("all")
    public static Class<? extends SocketChannel> getSocketChannel() {
        return EventLoops.socketChannel;
    }

    @java.lang.SuppressWarnings("all")
    public static Class<? extends ServerSocketChannel> getServerSocketChannel() {
        return EventLoops.serverSocketChannel;
    }
}
